services:
  chroma:
    image: chromadb/chroma:1.1.0
    container_name: chroma-chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma_chroma-data:/chroma/chroma_data
      - chroma_chroma-data:/data
    networks:
      - chroma-network
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
      - IS_PERSISTENT=TRUE
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2"]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
    restart: unless-stopped

  chroma-mcp:
    build:
      context: '.'  # Using relative path since we're already in the directory
    container_name: chroma-mcp
    volumes:
      - ./logs:/app/logs  # Mount a logs directory for log files
      - memory_chroma_data:/chroma-data  # Mount the data directory for persistent client
    environment:
      - CHROMA_CLIENT_TYPE=http
      - CHROMA_HOST=chroma-chroma
      - CHROMA_PORT=8000
      - CHROMA_SSL=false
      - TQDM_DISABLE=1  # Disable tqdm progress bars that interfere with JSON-RPC
    networks:
      - chroma-network
    depends_on:
      - chroma
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["sh", "-c", "tail -f /dev/null"]
    stdin_open: true
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

  chroma-streamable-http:
    build:
      context: '.'
    container_name: chroma-streamable-http
    ports:
      - "10550:10550"
    environment:
      - CHROMA_CLIENT_TYPE=http
      - CHROMA_HOST=chroma-chroma
      - CHROMA_PORT=8000
      - CHROMA_SSL=false
      - PYTHONUNBUFFERED=1
      - TQDM_DISABLE=1
      - ANONYMIZED_TELEMETRY=false
      - CHROMA_TELEMETRY_DISABLED=true
    networks:
      - chroma-network
    depends_on:
      - chroma
      - chroma-mcp
    command: ["python3", "-c", "from chroma_mcp.streamable_http_server import run_server; run_server('0.0.0.0', 10550)"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10550/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

networks:
  chroma-network:
    driver: bridge

volumes:
  memory_chroma_data:
    external: true
  chroma_chroma-data:
    external: true


