# Smithery configuration file: https://smithery.ai/docs/config#smitheryyaml

startCommand:
  type: stdio
  configSchema:
    # JSON Schema defining the configuration options for the MCP.
    type: object
    properties:
      clientType:
        type: string
        description: "The type of Chroma client to start: http, cloud, persistent, ephemeral"
        default: "ephemeral"
      dataDir:
        type: string
        description: "The directory to store the Chroma database if using the persistent client type"
      host:
        type: string
        description: "The host address of the Chroma server if using the http client type"
      port:
        type: number
        description: "The port number of the Chroma server if using the http client type"
      customAuthCredentials:
        type: string
        description: "The custom authentication credentials to use if using the http client type"
      tenant:
        type: string
        description: "The tenant name to use if using the cloud client type"
      database:
        type: string
        description: "The database name to use if using the cloud client type"
      apiKey:
        type: string
        description: "The API key to use if using the cloud client type"
      ssl:
        type: boolean
        description: "Whether to use SSL if using the http client type"
        default: true
          
  commandFunction:
    # A JS function that produces the CLI command based on the given config to start the MCP on stdio.
    |-
    (config) => ({ command: 'chroma-mcp', 
    args: [],
    env: {
      CHROMA_CLIENT_TYPE: config.clientType,
      CHROMA_DATA_DIR: config.dataDir,
      CHROMA_HOST: config.host,
      CHROMA_PORT: config.port,
      CHROMA_CUSTOM_AUTH_CREDENTIALS: config.customAuthCredentials,
      CHROMA_TENANT: config.tenant,
      CHROMA_DATABASE: config.database,
      CHROMA_API_KEY: config.apiKey,
      CHROMA_SSL: config.ssl,
    }
    })
  exampleConfig: {}
